/*
 * Copyright (c) 2013 ELL-i co-operative.
 */

#include <arduelli_gpio.h>

GPIO_INIT_DEFAULT_DEFINITION(A);
GPIO_INIT_DEFAULT_DEFINITION(B);
GPIO_INIT_DEFAULT_DEFINITION(C);
GPIO_INIT_DEFAULT_DEFINITION(D);
GPIO_INIT_DEFAULT_DEFINITION(F);

